enum PlayerName {
  mohamedSalah('Mohamed Salah'),
  riyadMahrez('Riyad Mahrez'),
  sadioMane('Sadio Mané'),
  hakimZiyech('Hakim Ziyech'),
  achrafHakimi('Achraf Hakimi'),
  youssefEnNesyri('Youssef En-Nesyri'),
  salemAlDawsari('Salem Al-Dawsari'),
  aliAlBulaihi('Ali Al-Bulaihi'),
  omarAlSomah('Omar Al-Somah'),
  ahmedHegazi('Ahmed Hegazi'),
  mahmoudDahoud('Mahmoud Dahoud'),
  nabilFekir('Nabil Fekir'),
  sofianeFeghouli('Sofiane Feghouli'),
  islamSlimani('Islam Slimani'),
  yacineBrahimi('Yacine Brahimi'),
  baghdadBounedjah('Baghdad Bounedjah'),
  ferjaniSassi('Ferjani Sassi'),
  wahbiKhazri('Wahbi Khazri'),
  amineHarit('Amine Harit'),
  sofyanAmrabat('Sofyan Amrabat'),
  noussairMazraoui('Noussair Mazraoui'),
  zakariaAboukhlal('Zakaria Aboukhlal'),
  abderrazakHamdallah('Abderrazak Hamdallah'),
  aliMaaloul('Ali Maaloul'),
  sebastienHaller('Sébastien Haller'),
  lionelMessi('Lionel Messi'),
  cristianoRonaldo('Cristiano Ronaldo'),
  neymarJr('Neymar Jr'),
  kylianMbappe('Kylian Mbappé'),
  kevinDeBruyne('Kevin De Bruyne'),
  robertLewandowski('Robert Lewandowski'),
  virgilVanDijk('Virgil van Dijk'),
  harryKane('Harry Kane'),
  karimBenzema('Karim Benzema'),
  erlingHaaland('Erling Haaland'),
  lukaModric('Luka Modrić'),
  sonHeungMin('Son Heung-min'),
  joshuaKimmich('Joshua Kimmich'),
  sergioAguero('Sergio Agüero'),
  paulPogba('Paul Pogba'),
  antoineGriezmann('Antoine Griezmann'),
  manuelNeuer('Manuel Neuer'),
  thiagoSilva('Thiago Silva'),
  ederson('Ederson Moraes'),
  raheemSterling('Raheem Sterling'),
  bernardoSilva('Bernardo Silva'),
  trentAlexanderArnold('Trent Alexander-Arnold'),
  marcusRashford('Marcus Rashford'),
  romeluLukaku('Romelu Lukaku'),
  alisson('Alisson Becker'),
  casemiro('Casemiro'),
  viniciusJr('Vinicius Jr'),
  rodri('Rodri Hernández'),
  federicoValverde('Federico Valverde'),
  judeBellingham('Jude Bellingham'),
  philFoden('Phil Foden'),
  bukayoSaka('Bukayo Saka'),
  jamalMusiala('Jamal Musiala'),
  pedri('Pedri González'),
  gavi('Pablo Gavi'),
  davidAlaba('David Alaba'),
  marquinhos('Marcos Aoás Corrêa'),
  toniKroos('Toni Kroos'),
  marcoReus('Marco Reus'),
  lautaroMartinez('Lautaro Martínez'),
  dusanVlahovic('Dušan Vlahović'),
  victorOsimhen('Victor Osimhen'),
  rafaelLeao('Rafael Leão'),
  darwinNunez('Darwin Núñez'),
  joaoFelix('João Félix'),
  rubenDias('Rúben Dias'),
  edinDzeko('Edin Džeko'),
  ivanRakitic('Ivan Rakitić'),
  marceloBrozovic('Marcelo Brozović'),
  milanSkriniar('Milan Škriniar'),
  kalidouKoulibaly('Kalidou Koulibaly'),
  gerardPique('Gerard Piqué'),
  sergioRamos('Sergio Ramos'),
  jordiAlba('Jordi Alba'),
  daniAlves('Dani Alves'),
  luisSuarez('Luis Suárez'),
  zlatanIbrahimovic('Zlatan Ibrahimović'),
  robertSanchez('Robert Sánchez'),
  unaiSimon('Unai Simón'),
  janOblak('Jan Oblak'),
  thibautCourtois('Thibaut Courtois'),
  moustafaMohamed('Mostafa Mohamed'),
  tarekHamed('Tarek Hamed'),
  amrWarda('Amr Warda'),
  mahmoudTrezeguet('Mahmoud Trezeguet'),
  aliouDieng('Aliou Dieng'),
  percyTau('Percy Tau'),
  mohamedElneny('Mohamed Elneny'),
  mohamedAbdelmonem('Mohamed Abdelmonem'),
  aliouBadji('Aliou Badji'),
  saadBguir('Saad Bguir'),
  yassineBounou('Yassine Bounou'),
  sofianeBoufal('Sofiane Boufal'),
  munirElHaddadi('Munir El Haddadi'),
  anassZaroury('Anass Zaroury'),
  abdessamadEzzalzouli('Abdessamad Ezzalzouli'),
  azzedineOunahi('Azzedine Ounahi'),
  bilalElKhannouss('Bilal El Khannouss'),
  salmanAlFaraj('Salman Al-Faraj'),
  firasAlBuraikan('Firas Al-Buraikan'),
  sultanAlGhannam('Sultan Al-Ghannam'),
  abdulelahAlMalki('Abdulelah Al-Malki'),
  aliAlHassan('Ali Al-Hassan'),
  nawafAlAbed('Nawaf Al-Abed'),
  yasserAlShahrani('Yasser Al-Shahrani'),
  mohammedAlOwais('Mohammed Al-Owais'),
  samiAlNajei('Sami Al-Najei'),
  hattanBahebri('Hattan Bahebri'),
  abdulrahmanGhareeb('Abdulrahman Ghareeb'),
  andreOnana('André Onana'),
  mikeMaignan('Mike Maignan'),
  giorgianDeArrascaeta('Giorgian De Arrascaeta'),
  nicolasOtamendi('Nicolás Otamendi'),
  enzoFernandez('Enzo Fernández'),
  julianAlvarez('Julián Álvarez'),
  alexisMacAllister('Alexis Mac Allister'),
  khvichaKvaratskhelia('Khvicha Kvaratskhelia'),
  takefusaKubo('Takefusa Kubo'),
  kaoruMitoma('Kaoru Mitoma'),
  leeKangIn('Lee Kang-in'),
  kimMinJae('Kim Min-jae'),
  heungMinSon('Son Heung-min'),
  takehiroTomiyasu('Takehiro Tomiyasu'),
  ritsuDoan('Ritsu Doan'),
  wataruEndo('Wataru Endo'),
  daichiKamada('Daichi Kamada'),
  mattyCash('Matty Cash'),
  wojciechSzczesny('Wojciech Szczęsny'),
  robertGumny('Robert Gumny'),
  jakubKiwior('Jakub Kiwior'),
  pietrZielinski('Piotr Zieliński'),
  arkadiuszMilik('Arkadiusz Milik'),
  niclasFullkrug('Niclas Füllkrug'),
  leroySane('Leroy Sané'),
  sergeGnabry('Serge Gnabry'),
  thomasMuller('Thomas Müller'),
  matthijsDeLigt('Matthijs de Ligt'),
  dayotUpamecano('Dayot Upamecano'),
  alphonsoDavies('Alphonso Davies'),
  kingsleyComan('Kingsley Coman'),
  joskoGvardiol('Joško Gvardiol'),
  lovroMajer('Lovro Majer'),
  domagojVida('Domagoj Vida'),
  lukaIvanusec('Luka Ivanušec'),
  andrejKramaric('Andrej Kramarić'),
  marceloSabitzer('Marcelo Sabitzer'),
  christophBaumgartner('Christoph Baumgartner'),
  konradLaimer('Konrad Laimer'),
  xaverSchlager('Xaver Schlager'),
  markoArnautovic('Marko Arnautović'),
  aleksandarDragovic('Aleksandar Dragović'),
  martinHinteregger('Martin Hinteregger'),
  stevenBergwijn('Steven Bergwijn'),
  memphisDepay('Memphis Depay'),
  codyGakpo('Cody Gakpo'),
  frenkieDeJong('Frenkie de Jong'),
  nathanAke('Nathan Aké'),
  daleyBlind('Daley Blind'),
  denzelDumfries('Denzel Dumfries'),
  jeremieFrimpong('Jérémie Frimpong'),
  teunKoopmeiners('Teun Koopmeiners'),
  martenDeRoon('Marten de Roon'),
  davyKlaassen('Davy Klaassen'),
  woutWeghorst('Wout Weghorst'),
  luukDeJong('Luuk de Jong'),
  noaLang('Noa Lang'),
  xaviSimons('Xavi Simons'),
  ryanGravenberch('Ryan Gravenberch'),
  devyneRensch('Devyne Rensch'),
  jurrienTimber('Jurriën Timber'),
  svenBotman('Sven Botman'),
  tyrellMalacia('Tyrell Malacia'),
  pascalStruijk('Pascal Struijk'),
  kennyTete('Kenny Tete'),
  jerdySchouten('Jerdy Schouten'),
  guusTil('Guus Til'),
  brianBrobbey('Brian Brobbey'),
  dusanTadic('Dušan Tadić'),
  sergejMilinkovicSavic('Sergej Milinković-Savić'),
  filipKostic('Filip Kostić'),
  aleksandarMitrovic('Aleksandar Mitrović'),
  lukaJovic('Luka Jović'),
  nikolaMilenkovic('Nikola Milenković'),
  strahinjaPavlovic('Strahinja Pavlović'),
  nemanjaGudelj('Nemanja Gudelj'),
  andrijaZivkovic('Andrija Živković'),
  darkoLazovic('Darko Lazović'),
  sasaLukic('Saša Lukić'),
  ivanIlic('Ivan Ilić'),
  nemanjaMaksimovic('Nemanja Maksimović'),
  filipDuricic('Filip Đuričić'),
  nemanjaRadonjic('Nemanja Radonjić'),
  lazaro('Lázaro'),
  pedro('Pedro'),
  gabrielJesus('Gabriel Jesus'),
  gabrielMartinelli('Gabriel Martinelli'),
  martinOdegaard('Martin Ødegaard'),
  emileSmithRowe('Emile Smith Rowe'),
  aaronRamsdale('Aaron Ramsdale'),
  benWhite('Ben White'),
  williamSaliba('William Saliba'),
  gabrielMagalhaes('Gabriel Magalhães'),
  oleksandrZinchenko('Oleksandr Zinchenko'),
  kieranTierney('Kieran Tierney'),
  thomasPartey('Thomas Partey'),
  jorginho('Jorginho'),
  granitXhaka('Granit Xhaka'),
  leandroTrossard('Leandro Trossard'),
  reissNelson('Reiss Nelson'),
  eddieNketiah('Eddie Nketiah'),
  fabioVieira('Fábio Vieira'),
  mattTurner('Matt Turner'),
  robHolding('Rob Holding'),
  cedricSoares('Cédric Soares'),
  albertSambiLokonga('Albert Sambi Lokonga'),
  nunoTavares('Nuno Tavares'),
  ainsleyMaitlandNiles('Ainsley Maitland-Niles'),
  nicolasPepe('Nicolas Pépé'),
  berndLeno('Bernd Leno'),
  alexandreLacazette('Alexandre Lacazette'),
  pierreEmerickAubameyang('Pierre-Emerick Aubameyang'),
  hectorBellerin('Héctor Bellerín'),
  lucasTorreira('Lucas Torreira'),
  matteoGuendouzi('Matteo Guendouzi'),
  mesutOzil('Mesut Özil'),
  alexIwobi('Alex Iwobi'),
  laurentKoscielny('Laurent Koscielny'),
  shkodranMustafi('Shkodran Mustafi'),
  seadKolasinac('Sead Kolašinac'),
  sokratisPapastathopoulos('Sokratis Papastathopoulos'),
  davidLuiz('David Luiz'),
  calumChambers('Calum Chambers'),
  krystianBielik('Krystian Bielik');

  final String fullName;

  const PlayerName(this.fullName);

  @override
  String toString() => fullName;
}
