enum TeamName {
  alAhly('Al Ahly'),
  zamalek('Zamalek'),
  pyramids('Pyramids FC'),
  ismaily('Ismaily SC'),
  alMasry('Al Masry'),
  enppi('ENPPI'),
  alIttihad('Al Ittihad Alexandria'),
  alMokawloon('Al Mokawloon Al Arab'),
  alHilal('Al Hilal'),
  alNassr('Al Nassr'),
  alIttihadJeddah('Al Ittihad Jeddah'),
  alAhliSaudi('Al Ahli Saudi'),
  alShabab('Al Shabab'),
  alFaisaly('Al Faisaly'),
  alRaed('Al Raed'),
  alTaawoun('Al Taawoun'),
  manUnited('Manchester United'),
  liverpool('Liverpool'),
  arsenal('Arsenal'),
  chelsea('Chelsea'),
  manCity('Manchester City'),
  tottenham('Tottenham Hotspur'),
  leicester('Leicester City'),
  westHam('West Ham United'),
  everton('Everton'),
  astonVilla('Aston Villa'),
  newcastle('Newcastle United'),
  wolves('Wolverhampton Wanderers'),
  leeds('Leeds United'),
  southampton('Southampton'),
  brighton('Brighton & Hove Albion'),
  crystalPalace('Crystal Palace'),
  barcelona('FC Barcelona'),
  realMadrid('Real Madrid'),
  atletico('Atletico Madrid'),
  sevilla('Sevilla FC'),
  valencia('Valencia CF'),
  villarreal('Villarreal CF'),
  realBetis('Real Betis'),
  realSociedad('Real Sociedad'),
  athleticBilbao('Athletic Bilbao'),
  juventus('Juventus'),
  inter('Inter Milan'),
  acMilan('AC Milan'),
  roma('AS Roma'),
  lazio('Lazio'),
  napoli('Napoli'),
  atalanta('Atalanta'),
  fiorentina('Fiorentina'),
  bayernMunich('Bayern Munich'),
  dortmund('Borussia Dortmund'),
  leipzig('RB Leipzig'),
  leverkusen('Bayer Leverkusen'),
  wolfsburg('VfL Wolfsburg'),
  gladbach('Borussia Mönchengladbach'),
  hoffenheim('TSG Hoffenheim'),
  frankfurt('Eintracht Frankfurt'),
  psg('Paris Saint-Germain'),
  lyon('Olympique Lyon'),
  marseille('Olympique Marseille'),
  monaco('AS Monaco'),
  lille('LOSC Lille'),
  nice('OGC Nice'),
  rennes('Stade Rennais'),
  saintEtienne('Saint-Étienne'),
  benfica('Benfica'),
  porto('FC Porto'),
  sporting('Sporting CP'),
  braga('SC Braga'),
  ajax('Ajax'),
  psv('PSV Eindhoven'),
  feyenoord('Feyenoord'),
  galatasaray('Galatasaray'),
  fenerbahce('Fenerbahçe'),
  besiktas('Beşiktaş'),
  trabzonspor('Trabzonspor'),
  riverPlate('River Plate'),
  bocaJuniors('Boca Juniors'),
  flamengo('Flamengo'),
  palmeiras('Palmeiras'),
  santos('Santos'),
  corinthians('Corinthians'),
  nacional('Nacional'),
  penarol('Peñarol'),
  alSadd('Al Sadd'),
  alDuhail('Al Duhail'),
  urawa('Urawa Red Diamonds'),
  kashima('Kashima Antlers'),
  jeonbuk('Jeonbuk Hyundai Motors'),
  suwon('Suwon Samsung Bluewings'),
  shanghai('Shanghai SIPG'),
  guangzhou('Guangzhou Evergrande'),
  nottinghamForest('Nottingham Forest'),
  blackburn('Blackburn Rovers'),
  deportivo('Deportivo La Coruña'),
  sampdoria('Sampdoria'),
  parma('Parma Calcio 1913'),
  laCoruna('Deportivo La Coruña'),
  celtic('Celtic'),
  rangers('Rangers'),
  dynamoKyiv('Dynamo Kyiv'),
  shakhtar('Shakhtar Donetsk'),
  olympiacos('Olympiacos'),
  panathinaikos('Panathinaikos'),
  anderlecht('Anderlecht'),
  clubBrugge('Club Brugge'),
  fcCopenhagen('FC Copenhagen'),
  malmo('Malmö FF'),
  redBullSalzburg('Red Bull Salzburg'),
  basel('FC Basel'),
  youngBoys('Young Boys'),
  zenit('Zenit Saint Petersburg'),
  cskaMoscow('CSKA Moscow'),
  spartakMoscow('Spartak Moscow'),
  dinamoZagreb('Dinamo Zagreb'),
  redStar('Red Star Belgrade'),
  partizan('Partizan Belgrade'),
  legia('Legia Warsaw'),
  slaviaPrague('Slavia Prague'),
  plzen('Viktoria Plzeň'),
  ferencvaros('Ferencváros'),
  apoel('APOEL Nicosia'),
  kaizerChiefs('Kaizer Chiefs'),
  orlandoPirates('Orlando Pirates'),
  alMerrikh('Al Merrikh'),
  esperance('Espérance de Tunis'),
  wydad('Wydad Casablanca'),
  raja('Raja Casablanca'),
  tpMazembe('TP Mazembe'),
  alMerreikh('Al Merreikh'),
  alHilalOmdurman('Al Hilal Omdurman'),
  alAhlyTripoli('Al Ahly Tripoli'),
  esSetif('ES Sétif'),
  mcAlger('MC Alger'),
  hearts('Hearts of Oak'),
  asanteKotoko('Asante Kotoko'),
  enyimba('Enyimba'),
  sundowns('Mamelodi Sundowns'),
  simba('Simba SC'),
  yanga('Young Africans'),
  zesco('ZESCO United'),
  alAhlyBenghazi('Al Ahly Benghazi'),
  alIttihadTripoli('Al Ittihad Tripoli'),
  alAhlyDubai('Al Ahly Dubai'),
  alAin('Al Ain'),
  alJazira('Al Jazira'),
  alWahda('Al Wahda'),
  alWasl('Al Wasl'),
  alNasrDubai('Al Nasr Dubai'),
  alShababDubai('Al Shabab Dubai'),
  alZawraa('Al Zawraa'),
  alQuwa('Al Quwa Al Jawiya'),
  alShorta('Al Shorta'),
  alTalaba('Al Talaba'),
  alNajaf('Al Najaf'),
  alKarkh('Al Karkh'),
  alSinaa('Al Sinaa'),
  alKahraba('Al Kahraba'),
  alHudood('Al Hudood'),
  alMinaa('Al Minaa'),
  alNaft('Al Naft'),
  alSulaikh('Al Sulaikh'),
  alTijara('Al Tijara'),
  alShurta('Al Shurta'),
  alKadhimiya('Al Kadhimiya'),
  alQasim('Al Qasim'),
  alDiwaniya('Al Diwaniya'),
  alKut('Al Kut'),
  alSamawa('Al Samawa'),
  alHilla('Al Hilla'),
  alAmarah('Al Amarah'),
  alBasra('Al Basra'),
  alNasiriya('Al Nasiriya'),
  alShatra('Al Shatra'),
  alRifai('Al Rifai'),
  alKufa('Al Kufa'),
  alMuthanna('Al Muthanna'),
  alAnbar('Al Anbar'),
  alRamadi('Al Ramadi'),
  alFallujah('Al Fallujah'),
  alHadba('Al Hadba'),
  alMosul('Al Mosul'),
  alDahuk('Al Dahuk'),
  alSulaymaniya('Al Sulaymaniya'),
  alErbil('Al Erbil'),
  alKirkuk('Al Kirkuk'),
  alTuz('Al Tuz'),
  alKhanaqin('Al Khanaqin'),
  alJazeera('Al Jazeera'),
  alForat('Al Forat'),
  alEuphrates('Al Euphrates'),
  alDijla('Al Dijla'),
  alShamal('Al Shamal'),
  alJanoub('Al Janoub'),
  alWasat('Al Wasat'),
  alSharqiya('Al Sharqiya'),
  alGharbiya('Al Gharbiya'),
  alWusta('Al Wusta'),
  alFayhaa('Al Fayhaa'),
  alNoor('Al Noor'),
  alSalam('Al Salam'),
  alRiyadh('Al Riyadh'),
  alWahdaMecca('Al Wahda Mecca'),
  alFaisalyHarmah('Al Faisaly Harmah'),
  alHazem('Al Hazem'),
  alAdalah('Al Adalah'),
  alBatin('Al Batin'),
  alFayha('Al Fayha'),
  alRaedUnaizah('Al Raed Unaizah'),
  alTaee('Al Taee'),
  alJabalain('Al Jabalain'),
  alNahda('Al Nahda'),
  alSahel('Al Sahel'),
  alOrobah('Al Orobah'),
  alTaraji('Al Taraji'),
  alKawkab('Al Kawkab'),
  alShoalah('Al Shoalah'),
  alNajma('Al Najma'),
  alQadsiah('Al Qadsiah'),
  alArabi('Al Arabi'),
  alSalmiya('Al Salmiya'),
  alKuwait('Al Kuwait'),
  alQadsia('Al Qadsia'),
  alNaser('Al Naser'),
  alTadamon('Al Tadamon'),
  alFahaheel('Al Fahaheel'),
  alYarmouk('Al Yarmouk'),
  alShababKuwait('Al Shabab Kuwait'),
  alSulaibikhat('Al Sulaibikhat'),
  alJahra('Al Jahra'),
  alSahelKuwait('Al Sahel Kuwait'),
  alNaserKuwait('Al Naser Kuwait'),
  alTadamonKuwait('Al Tadamon Kuwait'),
  alFahaheelKuwait('Al Fahaheel Kuwait'),
  alYarmoukKuwait('Al Yarmouk Kuwait'),
  alSulaibikhatKuwait('Al Sulaibikhat Kuwait'),
  alJahraKuwait('Al Jahra Kuwait');

  final String displayName;

  const TeamName(this.displayName);

  @override
  String toString() => displayName;
}
